modLoader = "javafml"
loaderVersion = "[40,)"
license = "MIT"

[[mods]]
modId = "tarotcards"
version = "${file.jarVersion}"
displayName = "Tarot Cards"
authors = "shiroroku"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/tarot-cards"
description = '''
Adds the 22 Major Arcana Tarot Cards with unique passive bonuses
'''

[[dependencies.tarotcards]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.tarotcards]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,1.19)"
ordering = "NONE"
side = "BOTH"
