modLoader = "javafml"
loaderVersion = "[43,)"
license = "MIT"

[[mods]]
modId = "tarotcards"
version = "${file.jarVersion}"
displayName = "Tarot Cards"
authors = "shiroroku"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/tarot-cards"
description = '''
Adds the 22 Major Arcana Tarot Cards with unique passive bonuses
'''
[[dependencies.tarotcards]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.tarotcards]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,1.19.2)"
ordering = "NONE"
side = "BOTH"
